linters:
  disable:
    - errcheck
    - ineffassign
    - gosimple
  enable:
    - govet
    - gofmt
    - goimports
    - bodyclose
    - exhaustive
    - exportloopref
    - goimports

run:
  skip-files:
    - idl/base/error_code.go
    - idl/base/rpc_address.go
