name: Pull Request

on:
  push:
    branches: [ master, prepare_merge_to_pegasus ]
  pull_request:
    branches: [ master, prepare_merge_to_pegasus ]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        working-directory: go-client
        with:
          version: v1.29

  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.13.x]
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Test
      run: ./test.sh
      working-directory: go-client
    - uses: codecov/codecov-action@v1
      working-directory: go-client
